### ISSUE TITLE
Please add a license file and a screen shot

### ISSUE THREAD

**Issue by unixorn** [Thy-GoD/thy-god-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots in the readme so that users can see what they look like without having to install them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by Thy-GoD** [comment]
Hey thanks for writing this, I actually made this just yesterday and forgot to add screenshots.

Will definitely do that rn.

**Comment by Thy-GoD** [comment]
I've finished adding the Screenshots and License.

**Comment by Thy-GoD** [comment]
> I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots in the readme so that users can see what they look like without having to install them.
> 
> Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.
> 
> Thanks!

Hello, was wondering if you're still planning on adding my theme to your repo, as this issue has been open for a long time now.

**Comment by unixorn** [comment]
You didn't close the issue so I didn't see that it was done :-)
